export const A380_ENVELOPE = Object.freeze({
  standardRunwayWidthFt: 260,
  rotateSpeedKt: 170,
  rotationRateDegPerSecond: 3,
  liftoffPitchDeg: 10,
  initialClimbPitchDeg: 12.5,
  initialClimbVerticalSpeedFpm: 1_200,
  departureHeadingReleaseAglFt: 400,
  initialClimbSpeedKt: 210,
  flapRetractionSpeedKt: 210,
  enrouteSpeedKt: 230,
  emergencyTurnSpeedKt: 210,
  baseSpeedKt: 185,
  finalSpeedKt: 155,
  approachSpeedKt: 140,
  stableApproachMinKt: 132,
  stableApproachMaxKt: 148,
  maxTouchdownSpeedKt: 155,
  minCommandSpeedKt: 140,
  maxCommandSpeedKt: 250,
  takeoffFlapsDeg: 10,
  approachFlapsDeg: 20,
  landingFlapsDeg: 30,
} as const)
